language: go

go:
  - 1.5
  - tip

before_deploy:
  - GOARCH=386 GOOS=linux   go build -o TcpRoute2-linux-386
  - GOARCH=386 GOOS=darwin  go build -o TcpRoute2-darwin-386
  - GOARCH=386 GOOS=windows go build -o TcpRoute2-windows-386

deploy:
  provider: releases
  api_key: $CI_USER_TOKEN
  skip_cleanup: true
  file:
    - TcpRoute2-linux-386
    - TcpRoute2-darwin-386
    - TcpRoute2-windows-386
  on:
    tags: true
    all_branches: true
